version: '3.4'

services:
  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Movies.API/Dockerfile
    depends_on:
     - sqlserverexpress
  sqlserverexpress:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    container_name: sqlserverexpress
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: testapp123.
      MSSQL_PID: Developer
    ports:
      - 1433:1433