version: '3.4'

services:
  movies.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Server=192.168.1.164;Database=Movies;User Id=SA;Password=testapp123.; # Do not set 'localhost' or '127.0.0.1' instead another IP
    ports:
      - "5000:80"