version: '3.4'

services:
  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Movies.API/Dockerfile
    depends_on:
      sqlserverexpress:
        condition: service_healthy
  sqlserverexpress:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    container_name: sqlserverexpress
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: testapp123.
      MSSQL_PID: Express
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "testapp123." -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - 1433:1433